# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

schedules:
- cron: "0 2 1-7 * SUN"
  displayName: 25th 5:30 AM (IST) Every Month
  branches:
    include:
    - azure_test_branch

trigger:
- car_task_cucumber
- azure_test_branch

pool:
  vmImage: ubuntu-latest
  name: MyLocalPool
  demands:
  - agent.name -equals 01

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'
    options: '-DMyEnv1=$(MyEnv1) -DMyEnv2=$(MyEnv2)'
- task: CopyFiles@2
  inputs:
    Contents: |
        **/log/*.log
        **/surefire-reports/**
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'My artifact'
    publishLocation: 'Container'